=== marcinlos/GriegCounter/GriegCore/src/main/resources/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://case.iisg.agh.edu.pl/confluence/display/prpj13kpGriegCounter"
  xmlns:tns="https://case.iisg.agh.edu.pl/confluence/display/prpj13kpGriegCounter"
  elementFormDefault="qualified">


  <xs:attributeGroup name="classAttrGroup">
    <xs:attribute name="class" />
  </xs:attributeGroup>

  <xs:attributeGroup name="propertyAttrGroup">
    <xs:attribute name="name" type="xs:string" use="required" />
    <xs:attribute name="value" type="xs:string" />
  </xs:attributeGroup>

  <xs:attributeGroup name="typeAttrGroup">
    <xs:attribute name="type" type="xs:string" />
  </xs:attributeGroup>

  <!-- Properties -->

  <xs:complexType name="simplePropertyType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attributeGroup ref="tns:propertyAttrGroup" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="complexPropertyType">
    <xs:choice>

    </xs:choice>
    <xs:attribute name="type" type="xs:string" />
  </xs:complexType>

  <xs:complexType name="propertyType">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element name="string" type="tns:simplePropertyType" />
      <xs:element name="int" type="tns:simplePropertyType" />
      <xs:element name="long" type="tns:simplePropertyType" />
      <xs:element name="float" type="tns:simplePropertyType" />
      <xs:element name="value">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="tns:simplePropertyType">
              <xs:attributeGroup ref="tns:typeAttrGroup" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="property" type="tns:complexPropertyType" />
      <xs:any namespace="##other" />
    </xs:choice>
  </xs:complexType>

  <!-- Pipeline -->

  <xs:complexType name="pipelineElementType">
    <xs:all>
      <xs:element name="name" />
      <xs:element name="class" />
      <xs:element name="source" minOccurs="0" maxOccurs="1" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="assemblerType">
    <xs:attributeGroup ref="tns:classAttrGroup" />
  </xs:complexType>

  <xs:complexType name="pipelineType">
    <xs:sequence minOccurs="1" maxOccurs="unbounded">
      <xs:choice>
        <xs:element name="node" type="tns:pipelineElementType" />
        <xs:element name="assembler" type="tns:assemblerType" />
      </xs:choice>
    </xs:sequence>
  </xs:complexType>


  <!-- Main configuration content -->

  <xs:element name="grieg">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="properties" minOccurs="0"
          type="tns:propertyType" />
        <xs:element name="pipeline" type="tns:pipelineType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== marcinlos/GriegCounter/GriegCore/src/test/resources/xml/grieg/example-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<grieg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="https://case.iisg.agh.edu.pl/confluence/display/prpj13kpGriegCounter"
  xsi:schemaLocation="
       https://case.iisg.agh.edu.pl/confluence/display/prpj13kpGriegCounter 
       config.xsd">

  <!-- 
  <properties>
    <int name="resolution">10000</int>
    <int name="chunk-size">2048</int>
    <int name="hop-size">441</int>
  </properties>
  -->

  <pipeline>
    <node>
      <name>segmenter</name>
      <class>pl.edu.agh.ki.grieg.analysis.Segmenter</class>
      <source>ROOT</source>
    </node>
    <node>
      <name>compressor</name>
      <class>pl.edu.agh.ki.grieg.analysis.WaveCompressor</class>
      <source>segmenter</source>
    </node>
    <node>
      <name>hamming</name>
      <class>pl.edu.agh.ki.grieg.analysis.HammingSegmenter</class>
      <source>ROOT</source>
    </node>
  </pipeline>

</grieg>
